/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-11-04 23:14:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.hibernate.Session;
import com.cafe.dto.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.cafe.dto.User");
    _jspx_imports_classes.add("org.hibernate.Session");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Imbiss Cafe</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"./images/logo/mainlogo.png\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Chelsea+Market&family=Montserrat:wght@400;800;900&family=Bubblegum+Sans&family=Mali&family=Flamenco&family=Aclonica&family=Carter+One&family=Luckiest+Guy&family=Lato&family=Montserrat+Subrayada&family=Sarabun&family=Viga&family=Wellfleet&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./references/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./references/footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./references/navigationBar.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./references/animation.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--NavigationBar-->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\">\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item mb-2 mt-1\">\r\n");
      out.write("                    <a class=\"nav-link active\" href=\"index.jsp\">HOME</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item mb-2 mt-1\" >\r\n");
      out.write("                    <a class=\"nav-link\" href=\"menu.jsp\">VIEW OUR MENU</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            ");
 if(session.getAttribute("user") != null){ 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"dropdown ml-auto mr-5\">\r\n");
      out.write("\t\t\t  <button style=\"font-family: 'Chelsea Market'\"  class=\"btn btn-outline-light dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t    ");
      out.print( session.getAttribute("user") != null ? ((User)session.getAttribute("user")).getUserName():"Hello" );
      out.write("\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t  <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("\t\t\t    <a style=\"font-family: 'Montserrat'; font-size:15px\" class=\"dropdown-item\" href=\"account.htm\">Manage Account</a>\r\n");
      out.write("\t\t\t    <a style=\"font-family: 'Montserrat'; font-size:15px\" class=\"dropdown-item\" href=\"getCart.htm\">Cart</a>\r\n");
      out.write("\t\t\t    <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          \t\t<a style=\"font-family: 'Montserrat'; font-size:15px\" class=\"dropdown-item\" href=\"logout.htm\">Logout</a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 }else{
      out.write("\r\n");
      out.write("\t\t\t<div class=\"ml-auto mr-5\">\r\n");
      out.write("\t\t<!-- \t<a href=\"loginForm.htm\" class=\"btn btn-outline-secondary\">Login</a> -->\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-outline-light\" style=\"font-family: 'Chelsea Market'\" href=\"loginForm.htm\" role=\"button\">Login</a> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!--EndofNavigationBar-->\r\n");
      out.write("\r\n");
      out.write("    <!--Header-->\r\n");
      out.write("    <header class=\"header\" style=\"background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.6)), url('./images/background/bkg-menu.jpg') center/cover no-repeat fixed;\">\r\n");
      out.write("        <div class=\"hero\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"index.jsp\" style=\"margin-left:50%; margin-top:2%;\">\r\n");
      out.write("                <img id=\"main-logo\" src=\"./images/logo/mainlogo.png\" alt=\"LosPollosHermanos\" />\r\n");
      out.write("            </a>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <div class=\"searchbar\">\r\n");
      out.write("                <input class=\"search_input\" type=\"text\" name=\"\" placeholder=\"Search...\">\r\n");
      out.write("                <a href=\"#\" class=\"search_icon\"><i class=\"fas fa-search\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--EndofHeader-->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--WhatWeDo-->\r\n");
      out.write("    <div class=\"role\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <h1>\r\n");
      out.write("                Why Imbiss Cafe?\r\n");
      out.write("            </h1>\r\n");
      out.write("           ");
      out.write("\r\n");
      out.write("        </div><br><br>\r\n");
      out.write("        <div>\r\n");
      out.write("            <p>The need for free food is real. Same goes for a job that lets you be you. Here at our Cafeteria we'll work with all your needs\r\n");
      out.write("            . Bring your real self to do this thing. And have some fun too. <b>WE GET YOU. WE GOT YOU! </b></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"video-grid-container\">\r\n");
      out.write("        <div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"wwd-container\">\r\n");
      out.write("        <div class=\"wwd-franchise\">\r\n");
      out.write("            <div class=\"wwd-content\">\r\n");
      out.write("                <h5>FRANCHISING</h5>\r\n");
      out.write("                <h1>Become a Franchise</h1><br>\r\n");
      out.write("                <p>Our Cafeteria is constantly growing. From the first restaurant, we've continued to expand our vision to help other people become successful business owners by owning a franchise. We\r\n");
      out.write("                    look for franchisees who are committed to quality, not cutting corners.</p><br>\r\n");
      out.write("                <button>Learn more about Franchising</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"wwd-invesment\">\r\n");
      out.write("            <div class=\"wwd-content\">\r\n");
      out.write("                <h5>INVESTORS</h5>\r\n");
      out.write("                <h1>Investing in Quality</h1><br>\r\n");
      out.write("                <p>We believe in Quality! You will get the best quality food. That's our promise to you!</p>\r\n");
      out.write("                <br><br><button>SEE OUR PERFORMANCE</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--EndOfWhatWeDo-->\r\n");
      out.write("\r\n");
      out.write("    <!--ChickenSandwich-->\r\n");
      out.write("    <section class=\"chicken-sandwich\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <h1></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"chicken-sandwich-content\">\r\n");
      out.write("            <h1>Our food delivers-<br>and gets delivered.</h1><br><br><br>\r\n");
      out.write("            <p>If it's spicy you need, we got the OG Spicy Chicken Sandwich. We also got those Made to Crave chicken sandwiches your taste buds are dreaming about. Oh, and you know we're all about that nugg life.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--EndOfChickenSandwich-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--MenuSection-->\r\n");
      out.write("    <section class=\"menu\" id=\"menu\">\r\n");
      out.write("        <article class=\"menu-image\"></article>\r\n");
      out.write("        <article class=\"menu-text\">\r\n");
      out.write("            <div class=\"menu-text-center\"><br><br><br><br><br>\r\n");
      out.write("                <p>It's the best ingredients. The spiciest spices. All prepared with loving care! And always delivered with a friendly smile. That's our promise.</p>\r\n");
      out.write("                <!-- <p style=\"font-size: 15px; text-align: right;\">Gustavo Fring -- Owner and Proprietor</p> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <br><a href=\"./menu.jsp\">Explore</a><br>\r\n");
      out.write("                <!-- <img id=\"gustavo-image\" src=\"images/people/gus.png\" alt=\"Gustavo Fring\" /> -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--EndofMenuSection-->\r\n");
      out.write("\r\n");
      out.write("    <!--SpicyChicken-->\r\n");
      out.write("    <section class=\"spicy-chicken\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"spicy-chicken-content\">\r\n");
      out.write("            <form action=\"userMenu.htm\">\r\n");
      out.write("                <h1>Pick your chicken.<br> Get 2 for $5.</h1><br><br>\r\n");
      out.write("                <p>Chicken fans, this one goes out to you. We're serving up the hits with 2 for $5.</p>\r\n");
      out.write("                <br>\r\n");
      out.write("                <p>You can get all hot with a Spicy Chicken Sandwich and a 10 PC Spicy Nugg, or keep it cool with a Homestyle Chicken Sandwich and 10 PC Crispy Nugg. You can even double up on the nuggs if you want.</p>\r\n");
      out.write("                <br>\r\n");
      out.write("                <p>However you shuffle them, if chicken is your jam, this deal is gonna bring the house down.</p><br>\r\n");
      out.write("                <button>START YOUR ORDER</button><br><br><br>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--EndOfSpicyChicken-->\r\n");
      out.write("    <div style=\"clear: both;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--NutritionSection-->\r\n");
      out.write("    <section class=\"nutrition-section\">\r\n");
      out.write("        <div class=\"nutrition-content\">\r\n");
      out.write("            <h1>Nutrition Information</h1><br>\r\n");
      out.write("            <p>Allergens. Calories. Ingredients. Let's find something that checks all your boxes.</p>\r\n");
      out.write("            <br><button>Learn More</button><br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <img src=\"images/background/nutrition.jpg\" alt=\"Nutrition\" />\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"copyright-sprite\">\r\n");
      out.write("        <!--âSpriteâ is a registered trademark of The Coca-Cola Company. Trademarks are the property of their respective owner. *First of all, no, a side is not similar to a sandwich. But-->\r\n");
      out.write("        <p> If you don't like something you got for breakfast, you can either show us your original receipt-like, your legit receipt. No tricky stuff. Or you can contact our Customer Care, give them your receipt and contact info, and they'll\r\n");
      out.write("            take care of you. Either way, you gotta do it by 10:30 AM the next day. Bottled drinks and full combos don't count. No credit or refunds, and only one exchange per receipt. We ARE still a business, after all. Promotion available for a limited\r\n");
      out.write("            time at participating locations only. Subject to cancellation at any time. Geez. Lawyers, amirite?</p>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--EndOfNutritionSection-->\r\n");
      out.write("\r\n");
      out.write("    <!--Footer-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"footer-left\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Gift Card</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Contact Us</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"https://www.amc.com/privacy\" target=\"_blank\">Privacy Policy</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"https://www.amc.com/terms\" target=\"_blank\">Terms and Conditions</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                ");
 if(session.getAttribute("user") == null){ 
      out.write("\r\n");
      out.write("                <span><a href=\"loginForm.htm\">Sign in <i class=\"fas fa-sign-in-alt\"></i></a></span>\r\n");
      out.write("              ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer-right\">\r\n");
      out.write("                <a href=\"https://twitter.com/pratikghare888\" target=_blank><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"https://www.instagram.com/pratikghare_/\" target=_blank><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"https://www.facebook.com/pratikghare88\" target=_blank><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-copyright\">\r\n");
      out.write("            <h6>FOR ENTERTAINMENT PURPOSES.</h6>\r\n");
      out.write("            <h6>&copy; 2020 Pratik Ghare & Pratik Mohite. All Rights Reserved.</h6>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--EndOfFooter-->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
