/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-11-05 15:06:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cafe.dto.User;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar", Long.valueOf(1604153983133L));
    _jspx_dependants.put("jar:file:/C:/Users/prati/OneDrive/Desktop/Cafeteria/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Cafeteria/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1539572356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.cafe.dto.User");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fminlength_005fclass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspr_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fminlength_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspr_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fminlength_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Register | Imbiss Cafe</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"./images/logo/mainlogo.png\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Chelsea+Market&family=Montserrat:wght@400;800;900&family=Bubblegum+Sans&family=Mali&family=Flamenco&family=Aclonica&family=Carter+One&family=Luckiest+Guy&family=Lato&family=Montserrat+Subrayada&family=Sarabun&family=Viga&family=Wellfleet&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./references/feedback.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./references/footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./references/navigationBar.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./references/animation.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\t.form-control{\r\n");
      out.write("\t\tbackground: rgba(255, 255, 255, 0.4) !important;\r\n");
      out.write("    \t//border: none !important;\r\n");
      out.write("    \t//border: 1px solid #c0c0c0 !important;\r\n");
      out.write("    \t//outline: none !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t form input{\r\n");
      out.write("\t \t\r\n");
      out.write("\r\n");
      out.write("\t }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--NavigationBar-->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark sticky-top\">\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link \" href=\"./index.jsp\">HOME</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"./menu.jsp\">VIEW OUR MENU</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!--EndofNavigationBar-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--Heading-->\r\n");
      out.write("    <div class=\"main-heading\">\r\n");
      out.write("        <h1>Register</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--EndofHeading-->\r\n");
      out.write("\r\n");
      out.write("    <!--Form-->\r\n");
      out.write("    <div class=\"sub-part\">\r\n");
      out.write("        <p>Help us know you better, so that we can serve you better. Information provided herein will be used solely for research purposes and will not be sold to any third parties.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"main-form\">\r\n");
      out.write("        ");
      if (_jspx_meth_spr_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <div class=\"right-panel\">\r\n");
      out.write("            <img src=\"./images/history-culture/promote.png\" />\r\n");
      out.write("            <!-- <img src=\"./images/history-culture/give-back.png\" /> -->\r\n");
      out.write("            <img src=\"./images/history-culture/team.png\" />\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--EndOfForm-->\r\n");
      out.write("\r\n");
      out.write("   <!--Footer-->\r\n");
      out.write("   <footer>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"footer-left\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">Gift Card</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">Contact Us</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://www.amc.com/privacy\" target=\"_blank\">Privacy Policy</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://www.amc.com/terms\" target=\"_blank\">Terms and Conditions</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <span><a href=\"loginForm.htm\">Sign in  <i class=\"fas fa-sign-in-alt\"></i></a></span>\r\n");
      out.write("            <span><a href=\"./index.jsp\">HOME  <i class=\"fas fa-home\"></i></a></span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-right\">\r\n");
      out.write("            <a href=\"https://twitter.com/pratikghare888\" target=_blank><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/pratikghare_/\" target=_blank><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("            <a href=\"https://www.facebook.com/pratikghare88\" target=_blank><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-copyright\">\r\n");
      out.write("        <h6>FOR ENTERTAINMENT PURPOSES.</h6>\r\n");
      out.write("        <h6>&copy; 2020 Pratik Ghare & Pratik Mohite. All Rights Reserved.</h6>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!--EndOfFooter-->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spr_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_spr_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_spr_005fform_005f0_reused = false;
    try {
      _jspx_th_spr_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spr_005fform_005f0.setParent(null);
      // /register.jsp(68,8) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005fform_005f0.setAction("regUser.htm");
      // /register.jsp(68,8) null
      _jspx_th_spr_005fform_005f0.setDynamicAttribute(null, "class", "was-validated");
      // /register.jsp(68,8) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005fform_005f0.setMethod("post");
      // /register.jsp(68,8) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005fform_005f0.setCommandName("user");
      int[] _jspx_push_body_count_spr_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005fform_005f0 = _jspx_th_spr_005fform_005f0.doStartTag();
        if (_jspx_eval_spr_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <div class=\"flex-container\">\r\n");
            out.write("                <h5>Let us know you better*</h5><br>\r\n");
            out.write("                \r\n");
            out.write("                ");
            if (_jspx_meth_spr_005finput_005f0(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("<br>\r\n");
            out.write("               \r\n");
            out.write("                <input type=\"email\" name=\"userEmail\" class=\"form-control\" placeholder=\"Enter your Email*\" required=\"true\" /><br>\r\n");
            out.write("                ");
            if (_jspx_meth_spr_005fpassword_005f0(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("                <br><br>\r\n");
            out.write("                <h5>Contact Details*</h5><br>\r\n");
            out.write("                ");
            if (_jspx_meth_spr_005finput_005f1(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("<br>\r\n");
            out.write("                <select name=\"userCity\" id=\"select-list\" required>\r\n");
            out.write("                    <option value=\"-\">-- Select your city</option>\r\n");
            out.write("                    <option value=\"Pune\">Pune</option>\r\n");
            out.write("                    <option value=\"Mumbai\">Mumbai</option>\r\n");
            out.write("                    <option value=\"Indore\">Indore</option>\r\n");
            out.write("                    <option value=\"Sangli\">Sangli</option>\r\n");
            out.write("                    <option value=\"Jaipur\">Jaipur</option>\r\n");
            out.write("                    <option value=\"Ahemdabad\">Ahemdabad</option>\r\n");
            out.write("                    <option value=\"Gujrat\">Gujrat</option>\r\n");
            out.write("                    <option value=\"Ratlam\">Ratlam</option>\r\n");
            out.write("                   \t<option value=\"Hyderabad\">Hyderabad</option>\r\n");
            out.write("                   \t<option value=\"Chennai\">Chennai</option>\r\n");
            out.write("                   \t<option value=\"Agra\">Agra</option>\r\n");
            out.write("                   \t<option value=\"Raipur\">Raipur</option>\r\n");
            out.write("                   \t<option value=\"SriNagar\">SriNagar</option>\r\n");
            out.write("                   \t<option value=\"Amritsar\">Amritsar</option>\r\n");
            out.write("                   \t<option value=\"Lucknow\">Lucknow</option>\r\n");
            out.write("                    <option value=\"Nashik\">Nashik</option>\r\n");
            out.write("                    <option value=\"Nagpur\">Nagpur</option>\r\n");
            out.write("                    <option value=\"Surat\">Surat</option>\r\n");
            out.write("                    <option value=\"Kolkata\">Kolkata</option>\r\n");
            out.write("                </select>\r\n");
            out.write("               <br><br>\r\n");
            out.write("                <button id=\"submit\">Register</button>\r\n");
            out.write("            </div>\r\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_spr_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spr_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.reuse(_jspx_th_spr_005fform_005f0);
      _jspx_th_spr_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f0_reused = false;
    try {
      _jspx_th_spr_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /register.jsp(72,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f0.setPath("userName");
      // /register.jsp(72,16) null
      _jspx_th_spr_005finput_005f0.setDynamicAttribute(null, "placeholder", "Customer Name*");
      int[] _jspx_push_body_count_spr_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f0 = _jspx_th_spr_005finput_005f0.doStartTag();
        if (_jspx_th_spr_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody.reuse(_jspx_th_spr_005finput_005f0);
      _jspx_th_spr_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:password
    org.springframework.web.servlet.tags.form.PasswordInputTag _jspx_th_spr_005fpassword_005f0 = (org.springframework.web.servlet.tags.form.PasswordInputTag) _005fjspx_005ftagPool_005fspr_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fminlength_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.PasswordInputTag.class);
    boolean _jspx_th_spr_005fpassword_005f0_reused = false;
    try {
      _jspx_th_spr_005fpassword_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spr_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /register.jsp(75,16) null
      _jspx_th_spr_005fpassword_005f0.setDynamicAttribute(null, "class", "form-control");
      // /register.jsp(75,16) null
      _jspx_th_spr_005fpassword_005f0.setDynamicAttribute(null, "minlength", "6");
      // /register.jsp(75,16) null
      _jspx_th_spr_005fpassword_005f0.setDynamicAttribute(null, "required", "true");
      // /register.jsp(75,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005fpassword_005f0.setPath("userPass");
      // /register.jsp(75,16) null
      _jspx_th_spr_005fpassword_005f0.setDynamicAttribute(null, "placeholder", "Enter your Password*");
      int[] _jspx_push_body_count_spr_005fpassword_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005fpassword_005f0 = _jspx_th_spr_005fpassword_005f0.doStartTag();
        if (_jspx_th_spr_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005fpassword_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005fpassword_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005fpassword_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005fpassword_0026_005frequired_005fplaceholder_005fpath_005fminlength_005fclass_005fnobody.reuse(_jspx_th_spr_005fpassword_005f0);
      _jspx_th_spr_005fpassword_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005fpassword_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005fpassword_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f1_reused = false;
    try {
      _jspx_th_spr_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /register.jsp(78,16) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f1.setPath("userPhone");
      // /register.jsp(78,16) null
      _jspx_th_spr_005finput_005f1.setDynamicAttribute(null, "placeholder", "Mobile No.*");
      int[] _jspx_push_body_count_spr_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f1 = _jspx_th_spr_005finput_005f1.doStartTag();
        if (_jspx_th_spr_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody.reuse(_jspx_th_spr_005finput_005f1);
      _jspx_th_spr_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f1_reused);
    }
    return false;
  }
}
